# Permalinks
permalink:        /blog/:categories/:year/:month/:day/:title.html
relative_permalinks: true

# Setup
title:            Shuheng Gong
tagline:          shgong
url:              
paginate:         1
paginate_path:    "blog/:num/"
baseurl:          http://shgong.github.io/
author:
  name:           shgong
  url:            
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           


# This is the list of pages to incldue in the header of the website.
pages_list:       {'Archive':'/archive','Feed':'/atom.xml','About':'/'}