# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Blog
tagline:          shgong
url:              
paginate:         1
baseurl:          /
author:
  name:           shgong
  url:            
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           


# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}